export const site = {
  name: "Vezures",
  legalName: "VZ TECHNOLOGIES L.L.C",
  duns: "1370937",
  url: "https://vezures.xyz",
  email: "contact@vezures.xyz",
  github: "https://github.com/vezuresdotxyz",
  tagline: "Building cool stuff since 2015. Stablecoin and lending maxis.",
  projects: [
    {
      name: "MAHA",
      accent: "oklch(0.8 0.16 75)",
      href: "https://maha.xyz/",
      domain: "maha.xyz",
      description: "A decentralized stablecoin protocol.",
      tags: ["Stablecoin", "DeFi"],
    },
    {
      name: "ZeroLend",
      accent: "oklch(0.78 0.16 165)",
      href: "https://zerolend.xyz/",
      domain: "zerolend.xyz",
      description: "A multi-chain lending and borrowing protocol.",
      tags: ["Lending", "DeFi"],
    },
    {
      name: "TinyHumans",
      accent: "oklch(0.72 0.19 285)",
      href: "https://tinyhumans.ai/",
      domain: "tinyhumans.ai",
      description: "Open-source AI agents that work for you.",
      tags: ["AI", "Open Source"],
    },
    {
      name: "Chottu",
      accent: "oklch(0.74 0.18 350)",
      href: "https://chottu.tinyhumans.ai/",
      domain: "chottu.tinyhumans.ai",
      description: "A helper that lives in your chats and gets things done for you.",
      tags: ["AI", "Assistant"],
    },
  ],
} as const;
